### ISSUE TITLE
Include the official 500 point format

### ISSUE THREAD

**Issue by lankygibbon** [NicholasCBrown/legion-HQ-2.0#16]
Although a very minor request. The official format has slightly different list restrictions of only 1 commander maximum and 4 corps maximum.

https://images-cdn.fantasyflightgames.com/filer_public/52/ac/52ac3c8e-f20c-44c3-977a-f49a0d0eebb2/star_wars_legion_skirmish.pdf

**Comment by Electrynth** [comment]
This is implemented. If you click the button that has the points value of the list it will cycle between Standard (800pts), Skirmish (500pts), and Grand Army (1600pts). Thanks!

**Comment by lankygibbon** [comment]
Absolutely that portion is done, it's a very minor thing but it's the fact the official skirmish format is limited to a single commander. The current system highlights in red when you have three commanders not 2.
![chrome_dGPCq1cCc4](https://user-images.githubusercontent.com/1769036/74232746-55329980-4cc1-11ea-8c0a-d87521968084.png)
![chrome_rkVkaelG7R](https://user-images.githubusercontent.com/1769036/74232748-55cb3000-4cc1-11ea-9f7d-e1f58d203909.png)

**Comment by Electrynth** [comment]
Yes you are correct. Apologies for that; I just checked the corps requirement and assumed I did the other portion correctly. Corrected the commander requirement with fd8d6e2160fc0d120efc49256aa0f540b25b49ca
