### ISSUE TITLE
Support for full card image print

### ISSUE THREAD

**Issue by lankygibbon** [NicholasCBrown/legion-HQ-2.0#17]
This one may be slightly on the side of IP infringement may not be possible. I run and host Legion games for new people very regularly. I have all the cards and do my best to make sure I have them laid out and ready for the players I am teaching. Having a method of printing a list including the full card art for each card would be great as this would allow me to keep a library of lists with my four boxes of armies at the shop and just pul the list and the minis and be ready to go without reorganizing the cards depending on what the person wanted to play.

This could also be useful for home or casual players to limit what they need to bring to friends houses etc.

**Comment by Electrynth** [comment]
As you said this is very close to infringement and where I will draw the line. Now it is definitely possible to get the images of cards from anywhere on the internet (on an unrelated side note I think I have a folder in public/images with _a lot_ of images of the cards) but I will not build this functionality into the builder itself.
